import { StyleSheet } from "react-native";

export default StyleSheet.create({
  backButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  container: { flex: 1, backgroundColor: "#EEEEEE", paddingHorizontal: 16 },
  backButton: { marginBottom: 12 },
  headline5: { fontSize: 28, color: "#252827", fontFamily: "Urbanist", fontWeight: 600 },
  headline5Bold: {
    fontSize: 24,
    color: "#252827",
    fontFamily: "Urbanist",
    fontWeight: 600,
  },
  subtitle1: { fontSize: 20, color: "#252827", fontFamily: "Urbanist" },
  subtitle1Bold: {
    fontSize: 20,
    color: "#252827",
    fontFamily: "Urbanist",
    fontWeight: 600,
    marginBottom: 10,
  },
  priceText: {
    fontSize: 18,
    color: "#0071C1",
    fontFamily: "Urbanist",
    fontWeight: 600,
    marginBottom: 10,
  },
  body1: {
    fontSize: 16,
    color: "#5A5A5A",
    fontFamily: "Urbanist",
    marginBottom: 10,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    marginVertical: 8,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  button: {
    backgroundColor: "#FFD400",
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: "center",
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  buttonTextBold: {
    color: "#0071C1",
    fontSize: 16,
    fontFamily: "Urbanist",
    fontWeight: 600,
  },
  imageCover: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    marginBottom: 15,
  },
  buttonSmall: { marginTop: 8 },
});
